name: Notify pull requests.

on:
  - pull_request

jobs:
  notify:
    name: Send telegram notification w/ pr url
    runs-on: ubuntu-latest
    steps:

    - name: send custom message with args
      uses: appleboy/telegram-action@master
      env:
        PR_NUMBER: ${{ github.event.number }}
      with:
        to: ${{ secrets.TELEGRAM_BOT_CHAT }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "#frontend\n\nPull request update - https://github.com/better-notes/better-notes-web-client/pull/${{ env.PR_NUMBER }}"
        disable_web_page_preview: true
